{{ if .Values.buildnum.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "buildnum.name" . }}
  labels:
    app: {{ template "buildnum.name" . }}
spec:
  replicas: 1 # one canonical source of build numbers
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "buildnum.name" . }}
    spec:
      serviceAccountName: {{ template "buildnum.name" . }}
      terminationGracePeriodSeconds: {{ .Values.buildnum.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "buildnum.name" . }}
        image: {{ tpl .Values.buildnum.image.repository . }}:{{ tpl .Values.buildnum.image.tag . }}
        imagePullPolicy: {{ .Values.buildnum.imagePullPolicy }}
{{ if .Values.buildnum.args }}
        args:
{{ toYaml .Values.buildnum.args | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.buildnum.resources | indent 10 }}
        ports:
          - name: http
            containerPort: {{ .Values.buildnum.service.internalPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.buildnum.probe.liveness.path }}
            port: {{ .Values.buildnum.probe.liveness.port }}
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.buildnum.probe.readiness.path }}
            port: {{ .Values.buildnum.probe.readiness.port }}
          initialDelaySeconds: 10
          periodSeconds: 3
          timeoutSeconds: 600
        volumeMounts:
        - mountPath: /store
          name: {{ template "buildnum.name" . }}-volume
      volumes:
        - name: {{ template "buildnum.name" . }}-volume
          persistentVolumeClaim:
            claimName: {{ template "buildnum.name" . }}
{{ end }}
